import { User } from "@/components/User";
import Image from "next/image";

async function fetchUsers() {
  const res = await fetch('https://reqres.in/api/users');
  const data = await res.json();
  return data.data;
}


// export const metadata = {
//   title: 'My first next 13 app',
//   description: 'Generated by create next app',
//   keywodrs: 'next,react,app',
// }


const IndexPage = async () => {

  const users = await fetchUsers();

  return (
    <div>
      <h1 className="text-3xl">Contacts</h1>
      <ul className="justify-around">{ users.map( user =>  <User key={ user.id } user={ user } /> )}</ul>
    </div>
  )
}

export default IndexPage